pipeline {
    agent any

    environment {
        WORKSPACE_DIR = '/var/lib/jenkins/workspace/CI-CD-for-ML'
        DATASET_PATH = '/var/lib/jenkins/workspace/CI-CD-for-ML/Data/drug200.csv'
    }

    stages {
        stage('Prepare Environment') {
            steps {
                sh '''
                    if [ ! -d "${WORKSPACE_DIR}/venv" ]; then
                        python3 -m venv ${WORKSPACE_DIR}/venv
                    fi
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    . ${WORKSPACE_DIR}/venv/bin/activate
                    pip install -r ${WORKSPACE_DIR}/requirements.txt
                '''
            }
        }

        stage('Run Training Script') {
            steps {
                sh '''
                    . ${WORKSPACE_DIR}/venv/bin/activate
                    python3 ${WORKSPACE_DIR}/train.py ${DATASET_PATH}
                '''
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive the model and result directories generated by train.py
                archiveArtifacts artifacts: 'Results/**, Model/**', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo "Pipeline finished."
        }
    }
}
